
package ifmo.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 *
 */
@WebService(name = "BookWebService", targetNamespace = "http://webservices.ifmo/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BookWebService {


    /**
     *
     * @return
     *     returns java.util.List<ifmo.webservices.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://webservices.ifmo/", className = "ifmo.webservices.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://webservices.ifmo/", className = "ifmo.webservices.GetBooksResponse")
    public List<Book> getBooks();

    /**
     *
     * @param id
     * @return
     *     returns java.util.List<ifmo.webservices.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookById", targetNamespace = "http://webservices.ifmo/", className = "ifmo.webservices.GetBookById")
    @ResponseWrapper(localName = "getBookByIdResponse", targetNamespace = "http://webservices.ifmo/", className = "ifmo.webservices.GetBookByIdResponse")
    public List<Book> getBookById(
            @WebParam(name = "id", targetNamespace = "")
                    int id);

}